import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Vision Luxury Villas | True Relaxation',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'shortcut icon',
      type: 'image/svg+xml',
      url: '/icon.svg'
    }
  ]
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
